### ISSUE TITLE
Don't fight over linkdef configuration

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#123]
Right now if you deploy a manifest that has a linkdef between the same actor and provider as another manifest, and the values for that linkdef are different, the scalers will end up in an infinite loop fight as they notice that the values they are expecting are different. I have mitigated this in an upcoming PR, but we should probably have a way to indicate that a linkdef is managed by wadm. If it is managed by wadm, then the scaler will not try to delete and recreate if the values are different, but if it isn't managed, wadm can "take control" and set the right values

**Comment by autodidaddict** [comment]
For the time being, before we figure out an alternative to the way link definitions work, we should probably reject manifests that could create a conflicting link definition. @thomastaylor312 @connorsmith256 we talked about this a little bit earlier today. 

There are some long term design concerns that I think might make this situation less of a problem, but for now we should prevent users from creating an unstable and unpredictable environment.

I'd like to propose that wadm reject any manifest that contains a _different_ link definition for a previous link between the same actor, provider ID, and link name. If two manifests supply the same link definition with the same values, then wadm can just reuse it.

So, by way of example:
* Application A
    * Link from KeyValueCounter to KvRedis/default with value URL=localhost:6379
* Application B
    * Link from KeyValuecounter to KvRedis/default with value URL=localhost:6379
* Application C
    * Link from KeyValueCounter to KvRedis/default with value URL=superexample:6378  

If these application manifests were added in sequence, then Application A would deploy just fine. Application B would deploy and "reuse" (no-op) the previously existing link because the values are _identical_. Application C would be rejected because it attempts to define a conflicting link definition.

This does end up in a "first wins" scenario, where the order in which the manifests are submitted dictates which ones might be rejected, but at least it still prevents the scenario we want to avoid.

**Comment by lee-orr** [comment]
@autodidaddict @thomastaylor312 @brooksmtownsend @connorsmith256 Can I ask for more information about what the long term solutions for this would be? I've been trying to get wasmCloud to work on a home server, with the plan of hosting multiple apps on a single lattice - some of which would be using identical sets of elements (actor images + providers) with different values on the links. This would be, for example, to allow me to have multiple different static file hosts that provide different files based on port (or ideally, host name for the URL - if I have the time to contribute that to the http server), or for utilizing a single auth actor image to provide auth for different services at different endpoints.

**Comment by thomastaylor312** [comment]
@lee-orr I think the solution here for your use case is to use different link names for each of those actors + providers. That is 100% a supported use case and is the reason link names exist. The reasoning behind that is the "magic" behind how wasmCloud routes things without knowing where they are running. If you have the same actor, linked with the same provider, but doing different things, it wouldn't know how to route the requests properly. Link names provide that unique value.

**Comment by lee-orr** [comment]
Oh perfect - that's good to know. I had assumed that linked names are hard coded to the expectations of a given actor...

If this is the case - would it not make sense to append/prepend the names of the deployed app to the link names it generates, to prevent conflicts?

**Comment by thomastaylor312** [comment]
> I had assumed that linked names are hard coded to the expectations of a given actor

You do have to set the name in the actor right now. We have had various conversations in the past though about providing configuration to an actor on startup. Nothing concrete though

**Comment by lee-orr** [comment]
Are the names of the links discoverable from an actor's point of view?

**Comment by thomastaylor312** [comment]
Not right now, you have to set the link name when you create the sender for a contract (i.e. `KeyValueSender::new_with_link("link_name")`)

**Comment by brooksmtownsend** [comment]
Some of this should be addressed by #122, we should be able to validate that in order to accept a manifest there's no existing link definition between the same two components

**Comment by connorsmith256** [comment]
Noticed this was stale but I'm not sure if it's still an issue... @thomastaylor312 @brooksmtownsend

**Comment by brooksmtownsend** [comment]
We don't technically fight over linkdef configuration but we haven't resolved how to deal with conflicting config, so I think it can stay open

**Comment by brooksmtownsend** [comment]
This may be a little different when we get to unidirectional links, which is work that's going on in wasmCloud/wasmCloud now. Bumping to keep it alive and we'll reevaluate if we don't get there by the next stale interval.

**Comment by thomastaylor312** [comment]
I think we decided this becomes a non issue with #247, right @brooksmtownsend?

**Comment by brooksmtownsend** [comment]
Correct, after #247 configuration is managed both external to a linkdef and will be scoped per-application. If you run into an issue where you're fighting for config, it means you're messing with wadm 😉
