### ISSUE TITLE
Create a `PutModelRequest` type and change the put endpoint

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#74]
After talking with @brooksmtownsend we think that a manifest should always deploy by default when it is put, but this means we need a request body to indicate when we _don't_ want it to deploy immediately. So we'll need to modify the put endpoint to expect a different body

**Comment by thomastaylor312** [comment]
Note: This should happen either after wadm 0.4 work is done or in wadm 0.5

**Comment by brooksmtownsend** [comment]
I mostly think this would be nice from an initial perspective, consolidating the put/deploy action into one command which would make it easy for us. Perhaps we could have the `deploy` body take a manifest instead of a name as an alternative? e.g. `wash app deploy -f echo.yaml`

Trying to tie this closely to the way that `kubectl apply` works, which IMO is a great experience for starting out. Oneliner, idempotent, accepts a file or stdin, etc

**Comment by thomastaylor312** [comment]
I think how we present it as a `cli` is different from how we structure it as an API. I'm not opposed to adding a shorthand like you suggest, but as an API it might make more sense to keep updating data and deploying said data different parts of the API.

**Comment by thomastaylor312** [comment]
Def not stale

**Comment by vados-cosmonic** [comment]
Hey @brooksmtownsend is this still relevent? I certainly don't see a `PutModelRequest` type, but it's also been a year!

**Comment by brooksmtownsend** [comment]
I think the new wadm-client's `put_and_deploy_manifest` operation works pretty well for this! Up to @thomastaylor312 but I think we can close it, especially since this was written in terms of wadm 0.4/0.5

**Comment by thomastaylor312** [comment]
Yeah, I think we're good to close here
